import type { Metadata } from "next";
import { Sora } from "next/font/google";
import "./globals.css";
import Footer from "./components/footer";
import Navbar from "./components/navbar";

const soraSans = Sora({
  variable: "--font-sora-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Nono-llc",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${soraSans.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <Navbar/>
        {children}
        <Footer />
      </body>
    </html>
  );
}
